name: Geert Theys
description: select _ from random_thoughts
meta_description: in sana in corpore sano

markdown: redcarpet
redcarpet:
  extensions: [footnotes]
highlighter: rouge
logo: false
paginate: 5
baseurl: /
domain_name: "http://geerttheys.com"
google_analytics: "UA-18869272-1"

# Details for the RSS feed generator
url: "http://geerttheys.com"
author: "Geert Theys"
gems: [jekyll-paginate, jekyll-gist]

exclude:
  ["config", "Rakefile", "LICENSE.txt", "README.md", "Gemfile.lock", "Gemfile"]
